//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbstractFactory.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string id_usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Nick_Usuario { get; set; }
    }
}
